config/routes.rb
Rails.application.routes.draw do
  resources :urls
  get ':token'  => 'home#visit_shortened_url', as: :visit_shortened_url
  get ':token/info'  => 'home#shortened_url_info', as: :shortened_url_info
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "urls#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :url
  has_many :visits
end

app/models/url.rb
class Url < ApplicationRecord
  has_one :link # If we need has many relation it can be easily change
  has_many :visits, through: :link


  validates :original,
            :presence => true,
            :format => { :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix, 
                         :multiline => true,
                         :message => "Plase enter a valid URL." },
            :uniqueness => { :case_sensitive => false }

  after_create :create_shortened_url

  def create_shortened_url
    url_hash = Digest::SHA1.hexdigest(id.to_s)

    Link.create(identifier: url_hash, url: self)
  end

  def identifier
    link&.identifier
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :link

  validates :ip, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_url_from_token

  def visit_shortened_url
    begin
      visit = @link.visits.new(ip: request.remote_ip)
      visit.save
      redirect_to @link.url.original, allow_other_host: true
    rescue => e
      redirect_to root_path, notice: e.message
    end
  end

  def shortened_url_info
  end

  private

  def find_url_from_token
    @link = Link.find_by(identifier: params[:token])
    redirect_to root_path unless @link.present?
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]

  # GET /urls or /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1 or /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls or /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_url(@url), notice: "Url was successfully created." }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1 or /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to url_url(@url), notice: "Url was successfully updated." }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1 or /urls/1.json
  def destroy
    @url.destroy

    respond_to do |format|
      format.html { redirect_to urls_url, notice: "Url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.require(:url).permit(:original)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/home/shortened_url_info.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h2>Url Info</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Link</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> <%= @link.url.original %> </td>
        <td> 
          <%= link_to "Show", @link.url %> |
          <%= link_to "Visit Short Link", visit_shortened_url_path(@link.url.identifier) %> |
          <%= link_to "Edit", edit_url_path(@link.url) %>
        </td>
      <tr>
    </tbody>
  </table>
  <hr>
  <h2>Visitors Info</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Id</th>
        <th>Ip</th>
      </tr>
    </thead>
    <tbody>
      <% @link.visits.each do |visit| %>
        <tr>
          <td> <%= visit.id %> </td>
          <td> <%= visit.ip %> </td>
        <tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "Back", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyURL</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <% if url.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table">
      
    <tbody>
      <tr>
        <td style="border:none">
          <%= form.label :original, style: "display: block" %>
          <%= form.text_field :original %>
        </td>
      </tr>
      <tr style="border:none">
        <td style="border:none"><%= form.submit %></td>
      </tr>
    </tbody>
  </table>
 <% end %>

app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <tr>
    <td> <%= url.original %> </td>
    <td> 
      <%= link_to "Show", url %> |
      <%= link_to "Visit Short Link", visit_shortened_url_path(token: url.identifier) %> |
      <%= link_to "Edit", edit_url_path(url) %> |
      <%= link_to "Info", shortened_url_info_path(token: url.identifier) %>
    </td>
  <tr>
</div>

app/views/urls/edit.html.erb
<div class="container">
  <h2>Editing url</h2>

  <%= render "form", url: @url %>

  <br>

  <div>
    <%= link_to "Show this url", @url %> |
  <%= link_to "Back to urls", urls_path %>
  </div>
</div>

app/views/urls/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h2>Urls</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Link</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @urls.each do |url| %>
        <%= render url %>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New url", new_url_path %>
</div>

app/views/urls/new.html.erb
<div class="container">
  <h2>New url</h2>

  <%= render "form", url: @url %>

  <br>

  <div>
    <%= link_to "Back to urls", urls_path %>
  </div>
</div>

app/views/urls/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h2>Url</h2>
  
  <div>Link: <%= @url.original %></div>
  <br>
  <div><%= link_to "Visit Short Link", visit_shortened_url_path(@url.identifier) %></div>
  <div><%= link_to "Edit this url", edit_url_path(@url) %>
  </div>  
  <div><%= link_to "Back to urls", urls_path %></div>
  <br>
  <%= button_to "Destroy this url", @url, method: :delete %>
</div>